language: haskell
install:
  - cabal install lens vector-space criterion
  - cabal configure --flag -instance-num --enable-tests
  - cabal build
  - cabal haddock
  - cabal test --show-details=always
