language: haskell

before_install:
  - ./.travis.install-deps $mode --constraint="bytestring installed"

install:
  - cabal configure $mode
  - cabal build

script:
  - cabal test --show-details=always
  - cabal bench || true

env:
  - mode="-fWerror -fHLint --enable-tests --enable-benchmarks -O2"

