language: haskell

before_install:
  - ./.travis.install-deps $mode --constraint="bytestring installed"

install:
  - cabal configure $mode
  - cabal build

script:
  - cabal test --show-details=always
  - cabal bench || true
  - ./.travis.hlint

env:
  - mode="-f-instance-num -fWerror --enable-tests --enable-benchmarks"

