language: haskell

before_install:
  - ./.travis.install-deps $mode

install:
  - cabal configure $mode
  - cabal build

script:
  - cabal test --show-details=always
  - ./.travis.hlint

env:
  - mode="-f-instance-num -fWerror --enable-tests"

